### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by reihanian** [galio-org/galio-starter-kit#27]
First running: npm install 

Then

$ npm start

> @galio-org/galio@1.1.0 start C:\Users\Iman\Documents\Github\galio-starter-kit
> expo start

[01:31:20] Starting project at C:\Users\Iman\Documents\Github\galio-starter-kit
[01:31:21] Developer tools running on http://localhost:19002
[01:31:22] Some dependencies are incompatible with the installed expo package version:
[01:31:22]  - react-native-svg - expected version: 9.9.5 - actual version installed: 9.13.6
[01:31:22] Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
[01:31:27] error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class.
[01:31:27]
[01:31:27] Metro Bundler process exited with code 1
[01:31:27] Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (C:\Users\Iman\AppData\Roaming\npm\node_modules\expo-cli\node_modules\xdl\src\start\startLegacyReactNativeServerAsync.ts:271:16)
    at Object.onceWrapper (events.js:483:26)
    at ChildProcess.emit (events.js:376:20)
    at ChildProcess.emit (domain.js:470:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @galio-org/galio@1.1.0 start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @galio-org/galio@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Iman\AppData\Roaming\npm-cache\_logs\2021-06-10T08_31_27_555Z-debug.log

**Comment by outoftheb0x** [comment]
Same issue here. I have installed ```react-native-svg``` version ```9.9.5``` but still same error:

```
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. 
```

I am using Windows btw. Tried to switch node versions 12.3 but no success
